#!/bin/bash
 
#PBS -q gpu
#PBS -l select=1:ngpus=1:ncpus=4
#PBS -l walltime=24:00:00
#PBS -o /lustre/home/alukic/TAR/SCP/logs/train_reply_twitter_wo.olog
#PBS -e /lustre/home/alukic/TAR/SCP/logs/train_reply_twitter_wo.elog

# pozovi module
module load scientific/pytorch/2.0.0
 
# pomakni se u direktorij gdje se nalazi skripta
cd ${PBS_O_WORKDIR:-""}

export IMAGE_PATH="/lustre/home/alukic/eval_sandbox.sif"
 
# potjeraj skriptu korištenjem torchrun-multinode.sh
#torchrun-singlenode.sh /lustre/home/alukic/TAR/SCP/gather_data.py
#torchrun-singlenode.sh /lustre/home/alukic/TAR/SCP/train_source_BERT.py
torchrun-singlenode.sh /lustre/home/alukic/TAR/SCP/train_reply_BERT.py